export type FiveElement = '목' | '화' | '토' | '금' | '수';

export interface HanjaStrokeEntry {
  reading: string;
  strokes: number;
  element: FiveElement;
}

// 획수 끝자리 기반 오행 산출 (성명학 기준)
// 1,2→목 / 3,4→화 / 5,6→토 / 7,8→금 / 9,0→수
export function strokeToElement(strokes: number): FiveElement {
  const lastDigit = strokes % 10;
  if (lastDigit === 1 || lastDigit === 2) return '목';
  if (lastDigit === 3 || lastDigit === 4) return '화';
  if (lastDigit === 5 || lastDigit === 6) return '토';
  if (lastDigit === 7 || lastDigit === 8) return '금';
  return '수'; // 9, 0
}

interface HanjaStrokeData {
  reading: string;
  strokes: number;
}

// 인명 작명에서 자주 쓰이는 한자 우선 수록 (강희자전 원획 기준)
// element는 strokeToElement()로 자동 계산되므로 여기에는 reading/strokes만 기록
const HANJA_DATA: Record<string, HanjaStrokeData> = {
  嘉: { reading: '가', strokes: 14 },
  佳: { reading: '가', strokes: 8 },
  家: { reading: '가', strokes: 10 },
  可: { reading: '가', strokes: 5 },
  歌: { reading: '가', strokes: 14 },
  健: { reading: '건', strokes: 11 },
  建: { reading: '건', strokes: 9 },
  敬: { reading: '경', strokes: 13 },
  景: { reading: '경', strokes: 12 },
  京: { reading: '경', strokes: 8 },
  慶: { reading: '경', strokes: 15 },
  炅: { reading: '경', strokes: 8 },
  庚: { reading: '경', strokes: 8 },
  暻: { reading: '경', strokes: 16 },
  桂: { reading: '계', strokes: 10 },
  高: { reading: '고', strokes: 10 },
  光: { reading: '광', strokes: 6 },
  敎: { reading: '교', strokes: 11 },
  九: { reading: '구', strokes: 2 },
  國: { reading: '국', strokes: 11 },
  君: { reading: '군', strokes: 7 },
  奎: { reading: '규', strokes: 9 },
  圭: { reading: '규', strokes: 6 },
  揆: { reading: '규', strokes: 13 },
  根: { reading: '근', strokes: 10 },
  琴: { reading: '금', strokes: 13 },
  錦: { reading: '금', strokes: 16 },
  玘: { reading: '기', strokes: 8 },
  基: { reading: '기', strokes: 11 },
  起: { reading: '기', strokes: 10 },
  祈: { reading: '기', strokes: 9 },
  己: { reading: '기', strokes: 3 },
  妮: { reading: '니', strokes: 8 },
  娜: { reading: '나', strokes: 10 },
  多: { reading: '다', strokes: 6 },
  丹: { reading: '단', strokes: 4 },
  淡: { reading: '담', strokes: 12 },
  大: { reading: '대', strokes: 3 },
  度: { reading: '도', strokes: 9 },
  道: { reading: '도', strokes: 16 },
  桃: { reading: '도', strokes: 10 },
  東: { reading: '동', strokes: 8 },
  斗: { reading: '두', strokes: 4 },
  兜: { reading: '두', strokes: 11 },
  德: { reading: '덕', strokes: 15 },
  朗: { reading: '랑', strokes: 10 },
  良: { reading: '량', strokes: 7 },
  蓮: { reading: '련', strokes: 17 },
  鍊: { reading: '련', strokes: 17 },
  林: { reading: '림', strokes: 8 },
  莉: { reading: '리', strokes: 13 },
  理: { reading: '리', strokes: 12 },
  梨: { reading: '리', strokes: 11 },
  利: { reading: '리', strokes: 7 },
  俐: { reading: '리', strokes: 9 },
  吏: { reading: '리', strokes: 6 },
  潾: { reading: '린', strokes: 16 },
  燐: { reading: '린', strokes: 16 },
  麟: { reading: '린', strokes: 23 },
  玟: { reading: '민', strokes: 9 },
  旻: { reading: '민', strokes: 8 },
  敏: { reading: '민', strokes: 11 },
  旼: { reading: '민', strokes: 8 },
  珉: { reading: '민', strokes: 10 },
  閔: { reading: '민', strokes: 12 },
  民: { reading: '민', strokes: 5 },
  美: { reading: '미', strokes: 9 },
  微: { reading: '미', strokes: 13 },
  洙: { reading: '수', strokes: 10 },
  博: { reading: '박', strokes: 12 },
  朴: { reading: '박', strokes: 6 },
  凡: { reading: '범', strokes: 3 },
  炳: { reading: '병', strokes: 9 },
  炫: { reading: '현', strokes: 9 },
  輔: { reading: '보', strokes: 14 },
  普: { reading: '보', strokes: 12 },
  寶: { reading: '보', strokes: 20 },
  福: { reading: '복', strokes: 14 },
  斌: { reading: '빈', strokes: 12 },
  玢: { reading: '빈', strokes: 9 },
  彬: { reading: '빈', strokes: 11 },
  冰: { reading: '빙', strokes: 6 },
  士: { reading: '사', strokes: 3 },
  司: { reading: '사', strokes: 5 },
  思: { reading: '사', strokes: 9 },
  娑: { reading: '사', strokes: 10 },
  瑞: { reading: '서', strokes: 14 },
  書: { reading: '서', strokes: 10 },
  抒: { reading: '서', strokes: 8 },
  緖: { reading: '서', strokes: 15 },
  徐: { reading: '서', strokes: 10 },
  夕: { reading: '석', strokes: 3 },
  碩: { reading: '석', strokes: 14 },
  善: { reading: '선', strokes: 12 },
  宣: { reading: '선', strokes: 9 },
  仙: { reading: '선', strokes: 5 },
  鮮: { reading: '선', strokes: 17 },
  雪: { reading: '설', strokes: 11 },
  城: { reading: '성', strokes: 10 },
  成: { reading: '성', strokes: 7 },
  星: { reading: '성', strokes: 9 },
  晟: { reading: '성', strokes: 11 },
  昭: { reading: '소', strokes: 9 },
  素: { reading: '소', strokes: 10 },
  松: { reading: '송', strokes: 8 },
  秀: { reading: '수', strokes: 7 },
  洵: { reading: '순', strokes: 10 },
  淳: { reading: '순', strokes: 12 },
  順: { reading: '순', strokes: 12 },
  承: { reading: '승', strokes: 8 },
  昇: { reading: '승', strokes: 8 },
  勝: { reading: '승', strokes: 12 },
  始: { reading: '시', strokes: 8 },
  時: { reading: '시', strokes: 10 },
  詩: { reading: '시', strokes: 13 },
  植: { reading: '식', strokes: 12 },
  信: { reading: '신', strokes: 9 },
  新: { reading: '신', strokes: 13 },
  晨: { reading: '신', strokes: 11 },
  雅: { reading: '아', strokes: 12 },
  我: { reading: '아', strokes: 7 },
  安: { reading: '안', strokes: 6 },
  愛: { reading: '애', strokes: 13 },
  若: { reading: '약', strokes: 11 },
  陽: { reading: '양', strokes: 17 },
  彦: { reading: '언', strokes: 9 },
  如: { reading: '여', strokes: 6 },
  妍: { reading: '연', strokes: 7 },
  娟: { reading: '연', strokes: 10 },
  延: { reading: '연', strokes: 7 },
  沇: { reading: '연', strokes: 8 },
  然: { reading: '연', strokes: 12 },
  姸: { reading: '연', strokes: 9 },
  軟: { reading: '연', strokes: 11 },
  悅: { reading: '열', strokes: 11 },
  英: { reading: '영', strokes: 11 },
  榮: { reading: '영', strokes: 14 },
  映: { reading: '영', strokes: 9 },
  永: { reading: '영', strokes: 5 },
  穎: { reading: '영', strokes: 16 },
  譽: { reading: '예', strokes: 21 },
  藝: { reading: '예', strokes: 19 },
  禮: { reading: '예', strokes: 18 },
  吳: { reading: '오', strokes: 7 },
  玉: { reading: '옥', strokes: 5 },
  完: { reading: '완', strokes: 7 },
  容: { reading: '용', strokes: 10 },
  勇: { reading: '용', strokes: 9 },
  于: { reading: '우', strokes: 3 },
  佑: { reading: '우', strokes: 7 },
  宇: { reading: '우', strokes: 6 },
  祐: { reading: '우', strokes: 10 },
  羽: { reading: '우', strokes: 6 },
  友: { reading: '우', strokes: 4 },
  優: { reading: '우', strokes: 17 },
  禹: { reading: '우', strokes: 9 },
  元: { reading: '원', strokes: 4 },
  源: { reading: '원', strokes: 14 },
  圓: { reading: '원', strokes: 13 },
  苑: { reading: '원', strokes: 11 },
  偉: { reading: '위', strokes: 11 },
  唯: { reading: '유', strokes: 11 },
  柔: { reading: '유', strokes: 9 },
  裕: { reading: '유', strokes: 13 },
  有: { reading: '유', strokes: 6 },
  幼: { reading: '유', strokes: 5 },
  柳: { reading: '유', strokes: 9 },
  潤: { reading: '윤', strokes: 16 },
  尹: { reading: '윤', strokes: 4 },
  允: { reading: '윤', strokes: 4 },
  玧: { reading: '윤', strokes: 9 },
  恩: { reading: '은', strokes: 10 },
  銀: { reading: '은', strokes: 14 },
  宜: { reading: '의', strokes: 8 },
  義: { reading: '의', strokes: 13 },
  二: { reading: '이', strokes: 2 },
  以: { reading: '이', strokes: 5 },
  伊: { reading: '이', strokes: 6 },
  怡: { reading: '이', strokes: 9 },
  而: { reading: '이', strokes: 6 },
  異: { reading: '이', strokes: 11 },
  李: { reading: '이', strokes: 7 },
  仁: { reading: '인', strokes: 4 },
  人: { reading: '인', strokes: 2 },
  任: { reading: '임', strokes: 6 },
  臨: { reading: '임', strokes: 18 },
  子: { reading: '자', strokes: 3 },
  慈: { reading: '자', strokes: 14 },
  在: { reading: '재', strokes: 6 },
  才: { reading: '재', strokes: 4 },
  栽: { reading: '재', strokes: 10 },
  宰: { reading: '재', strokes: 10 },
  材: { reading: '재', strokes: 7 },
  哉: { reading: '재', strokes: 9 },
  貞: { reading: '정', strokes: 9 },
  廷: { reading: '정', strokes: 7 },
  正: { reading: '정', strokes: 5 },
  政: { reading: '정', strokes: 8 },
  情: { reading: '정', strokes: 12 },
  靜: { reading: '정', strokes: 16 },
  禎: { reading: '정', strokes: 14 },
  程: { reading: '정', strokes: 12 },
  亭: { reading: '정', strokes: 9 },
  濟: { reading: '제', strokes: 18 },
  帝: { reading: '제', strokes: 9 },
  祖: { reading: '조', strokes: 10 },
  助: { reading: '조', strokes: 7 },
  朝: { reading: '조', strokes: 12 },
  組: { reading: '조', strokes: 11 },
  宗: { reading: '종', strokes: 8 },
  珠: { reading: '주', strokes: 11 },
  周: { reading: '주', strokes: 8 },
  主: { reading: '주', strokes: 5 },
  朱: { reading: '주', strokes: 6 },
  宙: { reading: '주', strokes: 8 },
  俊: { reading: '준', strokes: 9 },
  濬: { reading: '준', strokes: 18 },
  埈: { reading: '준', strokes: 10 },
  準: { reading: '준', strokes: 14 },
  晙: { reading: '준', strokes: 11 },
  浚: { reading: '준', strokes: 11 },
  知: { reading: '지', strokes: 8 },
  志: { reading: '지', strokes: 7 },
  枝: { reading: '지', strokes: 8 },
  持: { reading: '지', strokes: 10 },
  芝: { reading: '지', strokes: 10 },
  祉: { reading: '지', strokes: 9 },
  智: { reading: '지', strokes: 12 },
  眞: { reading: '진', strokes: 10 },
  珍: { reading: '진', strokes: 10 },
  進: { reading: '진', strokes: 15 },
  振: { reading: '진', strokes: 11 },
  陳: { reading: '진', strokes: 16 },
  贊: { reading: '찬', strokes: 19 },
  燦: { reading: '찬', strokes: 17 },
  昌: { reading: '창', strokes: 8 },
  彩: { reading: '채', strokes: 11 },
  採: { reading: '채', strokes: 12 },
  澄: { reading: '청', strokes: 16 },
  草: { reading: '초', strokes: 12 },
  初: { reading: '초', strokes: 7 },
  春: { reading: '춘', strokes: 9 },
  忠: { reading: '충', strokes: 8 },
  泰: { reading: '태', strokes: 9 },
  太: { reading: '태', strokes: 4 },
  澤: { reading: '택', strokes: 17 },
  兌: { reading: '태', strokes: 7 },
  炭: { reading: '탄', strokes: 9 },
  兎: { reading: '토', strokes: 7 },
  晴: { reading: '청', strokes: 12 },
  河: { reading: '하', strokes: 9 },
  夏: { reading: '하', strokes: 10 },
  荷: { reading: '하', strokes: 13 },
  翰: { reading: '한', strokes: 16 },
  韓: { reading: '한', strokes: 17 },
  限: { reading: '한', strokes: 14 },
  海: { reading: '해', strokes: 11 },
  亨: { reading: '형', strokes: 7 },
  泫: { reading: '현', strokes: 9 },
  玄: { reading: '현', strokes: 5 },
  賢: { reading: '현', strokes: 15 },
  顯: { reading: '현', strokes: 23 },
  協: { reading: '협', strokes: 8 },
  衡: { reading: '형', strokes: 16 },
  好: { reading: '호', strokes: 6 },
  浩: { reading: '호', strokes: 11 },
  虎: { reading: '호', strokes: 8 },
  鎬: { reading: '호', strokes: 18 },
  豪: { reading: '호', strokes: 14 },
  紅: { reading: '홍', strokes: 9 },
  洪: { reading: '홍', strokes: 10 },
  禍: { reading: '화', strokes: 14 },
  和: { reading: '화', strokes: 8 },
  花: { reading: '화', strokes: 10 },
  華: { reading: '화', strokes: 14 },
  孝: { reading: '효', strokes: 7 },
  厚: { reading: '후', strokes: 9 },
  熙: { reading: '희', strokes: 13 },
  喜: { reading: '희', strokes: 12 },
  希: { reading: '희', strokes: 7 },
};

// HANJA_DATA에서 element를 획수 기반으로 자동 계산하여 HANJA_STROKES 생성
export const HANJA_STROKES: Record<string, HanjaStrokeEntry> = Object.fromEntries(
  Object.entries(HANJA_DATA).map(([char, data]) => [
    char,
    { ...data, element: strokeToElement(data.strokes) },
  ])
);

export function getHanjaStrokeEntry(character: string): HanjaStrokeEntry | undefined {
  return HANJA_STROKES[character];
}
